[package]
name = "ndn"
version = "0.0.1"
description = "[WIP] NDN - Named Data Networking in Rust"
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
homepage = "https://github.com/imp/ndn-rs"
keywords = ["ndn", "named", "data", "networking"]
license = "Apache-2.0/MIT"
repository = "https://github.com/imp/ndn-rs.git"
categories = ["network-programming"]

[badges]
travis-ci = { repository = "imp/ndn-rs" }
gitlab = { repository = "imp/ndn-rs" }

[dependencies]
bytes = "0.4"
